root: true

env:
    es6: true
    browser: true
    node: true

extends: airbnb

parser: babel-eslint

parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true
        experimentalObjectRestSpread: true

rules:
    # Guidelines
    comma-dangle: 0
    new-cap: [0, {capIsNew: true, newIsCap: true}]
    prefer-const: 2
    indent: [2, 2, {"SwitchCase": 1}]
    import/no-unresolved: [2, { "ignore": ["^(components|scenes|utils|reduxs|static)"] }]

    # React
    react/jsx-closing-bracket-location: [1, "after-props"]
    react/jsx-indent-props: [2, 2]
    react/prefer-stateless-function: 0
    react/prop-types: 0
